name: Build pipeline
on: [pull_request]

jobs:

  build:
    name: Build
    runs-on: ["self-hosted", "dev"]
    container: openjdk:16-alpine
    steps: 
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Compile project
        run: ./gradlew build